### PR TITLE
Fix student modal responsiveness

### PR DESCRIPTION
**Pull request by Tuzosdaniel12**
On this pull
Fixed Student Modal to have more optomized views

- Feed and details stack sooner, also added a tab on top of modal. Taps appear when screen is smaller then tablets, one can switch between edit students and activities views.
- Comment box collapse until clicked into, by using the detection hook on ```client/src/utils/detection.js```
- Added text wrap to comment box to wrap text when is longer the div width. 
- Added consistent height to modal 
- remove overflow auto from student modal to keep tap and comment box as fix items

### CODE REVIEW

**Review by ac524 — CHANGES_REQUESTED** [review]
Good start @Tuzosdaniel12. I'd like some fine tuning and other updates and enhancements addressed.

Please see ClickUp for full details :)

**Review by ac524 — CHANGES_REQUESTED** [review]
Great job getting the collapse behavior in place. I've got more change requests posted for you over in ClickUp to keep finessing this and resolve a few more issues.

Here's the quick breakdown
- Update collapsed view
- Fix shadow bleed over
- Address error in the console and issue with the form not finishing it's "submit"
- Fix the "Add Student" view that displays the modal without the activity feed

https://sharing.clickup.com/t/h/tkbxrj/58NNT6GZUTSB2JJ

**Review by ac524 — APPROVED** [review]
Hey @Tuzosdaniel12, was this ready for review? I added a few last style tweaks, but think it's ok to merge for now.

Think I will have a few more things I'd like you to address, but we can go over those on a follow up request.

**Comment by Tuzosdaniel12** [comment]
@ac524 let me know what other issues you would like me to address, I can get them done tonight.

**Comment by ac524** [comment]
Merging this request as is. Additional changes will be done through additional requests.

**Pull request merged**
